CC=g++
CFLAGS=-std=c++17
SOURCES=Bid.cpp Card.cpp Contract.cpp Game.cpp LibreBridge.cpp Misc.cpp Player.cpp

all:
	$(CC) $(CFLAGS) $(SOURCES) -o ../LibreBridge

#all: LibreBridge
#
#LibreBridge: test1.o test2.o LibreBridge.o
#	g++ test1.o test2.o -o LibreBridge

#test1.o: test1.cpp
#	$(CC) $(CFLAGS) -c test1.cpp

#test2.o: test2.cpp
#	$(CC) $(CFLAGS) -c test2.cpp

#LibreBridge.o: LibreBridge.cpp
#	$(CC) $(CFLAGS) -c LibreBridge.cpp